name: fluentx
description: "A new Dart FFI package project."
version: 0.0.1

environment:
  sdk: ^3.13.3

dependencies:
  code_assets: ^1.1.0
  flutter_rust_bridge: 2.13.0
  flutter_rust_bridge_hooks: 2.13.0
  hooks: ^2.0.0
  logging: ^1.3.0

dev_dependencies:
  ffi: ^2.1.4
  ffigen: ^20.1.1
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  test: ^1.28.0
